//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationusingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int TShirtSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }

        public override string ToString()
        {
            return (EmployeeId + "\t" +
                    EmployeeName + "\t" +
                    DateOfBirth + "\t" +
                    JoinDate + "\t" +
                    TShirtSize);
        }

    }
}
